"use client";

import { useMemo, useState } from "react";

type Brand = "Aluplast" | "Deceuninck";
type Tab = "Resumen" | "Diseño" | "Consumo" | "Servicios" | "Informes";
type Report = "Oferta"|"Producción"|"Perfiles"|"Herrajes"|"Vidrio"|"Costos";
type ViewMode = "Frente"|"Sección"|"3D";
type PaneSpec={state:string;opening:string;direction:string;hardware:string;handle:string;glass:string;notes:string};
type Layout = { id:string; name:string; group:string; panels:number; rails:number; moves:string; icon:string };
type System = { name:string; category:string; depth:number; chambers:string; glazing:number; maxW:number; maxH:number; rails:number[]; layouts:string[]; frame:number; sash:number; hardware:number; uf:string };

const layouts: Layout[] = [
  {id:"fixed",name:"Fijo",group:"Ventana",panels:1,rails:0,moves:"F",icon:"▣"},
  {id:"slide2",name:"Corrediza 2 hojas",group:"Corredera",panels:2,rails:2,moves:"LR",icon:"⇆"},
  {id:"slide3",name:"3 hojas · centro fijo",group:"Corredera",panels:3,rails:2,moves:"LFR",icon:"⇠▣⇢"},
  {id:"slide3all",name:"3 hojas móviles",group:"Corredera",panels:3,rails:3,moves:"LRL",icon:"⇆⇆⇆"},
  {id:"slide4",name:"4 hojas · 2 móviles",group:"Corredera",panels:4,rails:2,moves:"FLLF",icon:"▣⇆⇆▣"},
  {id:"mono",name:"Monorriel · fijo + móvil",group:"Corredera",panels:2,rails:1,moves:"FL",icon:"▣⇢"},
  {id:"casement",name:"Abatible interior",group:"Practicable",panels:1,rails:0,moves:"A",icon:"◩"},
  {id:"out",name:"Abatible exterior",group:"Practicable",panels:1,rails:0,moves:"O",icon:"◪"},
  {id:"tilt",name:"Oscilobatiente",group:"Practicable",panels:1,rails:0,moves:"T",icon:"⌂"},
  {id:"project",name:"Proyectante",group:"Practicable",panels:1,rails:0,moves:"P",icon:"▽"},
  {id:"door",name:"Puerta abatible",group:"Puerta",panels:1,rails:0,moves:"D",icon:"▥"},
  {id:"door2",name:"Puerta doble",group:"Puerta",panels:2,rails:0,moves:"DD",icon:"▥▥"},
  {id:"fold",name:"Plegable 3 hojas",group:"Especial",panels:3,rails:0,moves:"BBB",icon:"≪≪"},
  {id:"parallel",name:"Osciloparalela",group:"Especial",panels:2,rails:1,moves:"FT",icon:"▣⇥"},
  {id:"lift",name:"Elevadora corrediza",group:"Especial",panels:2,rails:2,moves:"FL",icon:"▣⇢"},
  {id:"hung",name:"Guillotina",group:"Especial",panels:2,rails:2,moves:"UD",icon:"⇅"},
];

const catalog: Record<Brand,System[]> = {
  Aluplast:[
    {name:"IDEAL 2000 MX · Corredera 2 rieles",category:"Corredera",depth:60,chambers:"3 cámaras",glazing:24,maxW:4000,maxH:2400,rails:[2],layouts:["slide2","slide3","slide4"],frame:155,sash:132,hardware:980,uf:"1.6 W/m²K"},
    {name:"IDEAL 2000 MX · Corredera 3 rieles",category:"Corredera",depth:60,chambers:"3 cámaras",glazing:24,maxW:4800,maxH:2400,rails:[3],layouts:["slide3all","slide4"],frame:178,sash:132,hardware:1360,uf:"1.6 W/m²K"},
    {name:"IDEAL 2000 MX · Monorriel",category:"Corredera",depth:60,chambers:"3 cámaras",glazing:24,maxW:4000,maxH:2400,rails:[1],layouts:["mono","slide3"],frame:168,sash:137,hardware:1080,uf:"1.6 W/m²K"},
    {name:"IDEAL 2000 Classic-line · Fijo",category:"Fijo",depth:60,chambers:"3 cámaras",glazing:33,maxW:3000,maxH:2600,rails:[0],layouts:["fixed"],frame:172,sash:0,hardware:180,uf:"1.6 W/m²K"},
    {name:"IDEAL 2000 Classic-line · Practicable",category:"Practicable",depth:60,chambers:"3 cámaras",glazing:33,maxW:2800,maxH:2400,rails:[0],layouts:["fixed","casement","out","tilt","project"],frame:188,sash:172,hardware:1850,uf:"1.6 W/m²K"},
    {name:"IDEAL 2000 Round-line · Practicable",category:"Practicable",depth:60,chambers:"3 cámaras",glazing:33,maxW:2800,maxH:2400,rails:[0],layouts:["fixed","casement","out","tilt","project"],frame:196,sash:180,hardware:1850,uf:"1.6 W/m²K"},
    {name:"IDEAL 2000 · Puerta interior/exterior",category:"Puerta",depth:60,chambers:"3 cámaras",glazing:33,maxW:2400,maxH:2600,rails:[0],layouts:["door","door2"],frame:205,sash:198,hardware:2480,uf:"1.6 W/m²K"},
    {name:"IDEAL 2000 · Osciloparalela",category:"Especial",depth:60,chambers:"3 cámaras",glazing:33,maxW:3600,maxH:2400,rails:[1],layouts:["parallel"],frame:218,sash:192,hardware:3900,uf:"1.6 W/m²K"},
    {name:"IDEAL 4000 70",category:"Practicable",depth:70,chambers:"5 cámaras",glazing:41,maxW:3000,maxH:2600,rails:[0],layouts:["fixed","casement","out","tilt","project","door","door2","fold","parallel"],frame:208,sash:191,hardware:2150,uf:"1.3 W/m²K"},
    {name:"smart-slide 70",category:"Especial",depth:70,chambers:"cierre perimetral",glazing:41,maxW:5800,maxH:2400,rails:[1,2],layouts:["mono","slide2","slide3","slide4","parallel"],frame:245,sash:218,hardware:4200,uf:"1.3 W/m²K"},
    {name:"Lift-slide 85",category:"Especial",depth:85,chambers:"umbral especial",glazing:52,maxW:6500,maxH:2800,rails:[2],layouts:["lift","slide4"],frame:320,sash:285,hardware:7600,uf:"1.1 W/m²K"},
  ],
  Deceuninck:[
    {name:"Sliding 2 rieles",category:"Corredera",depth:60,chambers:"multicámara",glazing:24,maxW:4000,maxH:2400,rails:[2],layouts:["slide2","slide3","slide4","hung"],frame:148,sash:126,hardware:930,uf:"según configuración"},
    {name:"Sliding Monorriel",category:"Corredera",depth:60,chambers:"multicámara",glazing:24,maxW:4000,maxH:2400,rails:[1],layouts:["mono","slide3"],frame:164,sash:132,hardware:1040,uf:"según configuración"},
    {name:"Bella Sliding",category:"Corredera",depth:80,chambers:"multicámara",glazing:24,maxW:5200,maxH:2600,rails:[2,3],layouts:["slide2","slide3","slide3all","slide4"],frame:176,sash:151,hardware:1180,uf:"según configuración"},
    {name:"Bella Sliding Monorriel",category:"Corredera",depth:80,chambers:"multicámara",glazing:24,maxW:5200,maxH:2600,rails:[1],layouts:["mono","slide3"],frame:185,sash:158,hardware:1290,uf:"según configuración"},
    {name:"Everest Max 60",category:"Practicable",depth:60,chambers:"4 cámaras · doble junta",glazing:36,maxW:3000,maxH:2600,rails:[0],layouts:["fixed","casement","out","tilt","project","door","door2","fold","parallel"],frame:182,sash:168,hardware:1780,uf:"según vidrio"},
    {name:"Lotus Sliding",category:"Corredera",depth:76,chambers:"multicámara",glazing:24,maxW:4800,maxH:2500,rails:[1,2],layouts:["mono","slide2","slide3","slide4"],frame:194,sash:164,hardware:1380,uf:"según configuración"},
    {name:"Legend / Legend Slide",category:"Premium",depth:80,chambers:"multicámara",glazing:44,maxW:5200,maxH:2700,rails:[0,1,2],layouts:["fixed","casement","tilt","door","mono","slide2","parallel"],frame:238,sash:207,hardware:2450,uf:"alto desempeño"},
    {name:"HS-76 Elevadora",category:"Especial",depth:175,chambers:"elevadora",glazing:52,maxW:6500,maxH:2800,rails:[2],layouts:["lift","slide4"],frame:310,sash:278,hardware:7200,uf:"según configuración"},
  ]
};

const ideal2000Profiles = [
  {code:"102071171",name:"Marco 3 rieles para ventana corrediza 60 mm con junta · JB",role:"Marco",status:"Código de lista MX"},
  {code:"102372171",name:"Hoja para ventana corrediza 60 mm con junta · JB",role:"Hoja",status:"Código de lista MX"},
  {code:"620116",name:"Unión mecánica para travesaño / montante",role:"Conector",status:"IDEAL 2000 / 4000"},
  {code:"120x07",name:"Marco Classic-line 70 × 60 mm",role:"Marco",status:"Catálogo técnico"},
  {code:"120x18",name:"Marco Round-line 70 × 60 mm",role:"Marco",status:"Catálogo técnico"},
  {code:"120x41",name:"Poste / travesaño Classic-line 80 mm",role:"Travesaño",status:"Catálogo técnico"},
  {code:"120x45",name:"Poste / travesaño Round-line 80 mm",role:"Travesaño",status:"Catálogo técnico"},
  {code:"120x35",name:"Hoja exterior Classic-line 120 mm",role:"Hoja",status:"Catálogo técnico"},
  {code:"120x86",name:"Hoja de encuentro Round-line 49 mm",role:"Hoja",status:"Catálogo técnico"},
  {code:"120833/120863",name:"Junquillo para combinaciones de 24 mm",role:"Junquillo",status:"Según acristalamiento"},
];

const glassCatalog = [
  {name:"Cristal recocido claro 6 mm",thickness:6,price:354.84,type:"Monolítico"},{name:"Cristal recocido claro 9.5 mm",thickness:9.5,price:560.28,type:"Monolítico"},{name:"Cristal recocido claro 12.7 mm",thickness:12.7,price:784.39,type:"Monolítico"},
  {name:"Cristal templado claro 6 mm",thickness:6,price:505.18,type:"Seguridad"},{name:"Cristal templado claro 9.5 mm",thickness:9.5,price:810.84,type:"Seguridad"},{name:"Cristal templado claro 12.7 mm",thickness:12.7,price:1110.12,type:"Seguridad"},
  {name:"Luna clara 6 mm",thickness:6,price:993.30,type:"Especial"},{name:"DVH 24 mm · 6/12/6",thickness:24,price:1650,type:"Doble vidrio"},{name:"DVH 20 mm · 4/12/4",thickness:20,price:1420,type:"Doble vidrio"},{name:"Laminado 6+6 mm",thickness:12.7,price:1890,type:"Seguridad"}
];

const colors:Record<Brand,{name:string;code:string;factor:number}[]> = {
  Aluplast:[{name:"Blanco",code:"BL",factor:1},{name:"Negro JB",code:"JB",factor:1.18},{name:"Antracita",code:"ANT",factor:1.22},{name:"Nogal",code:"NOG",factor:1.24},{name:"Roble dorado",code:"RD",factor:1.24}],
  Deceuninck:[{name:"Blanco",code:"M3",factor:1},{name:"Roble Dorado",code:"190",factor:1.21},{name:"Nogal",code:"191",factor:1.22},{name:"Macoré",code:"149",factor:1.22},{name:"Mountain Oak",code:"196",factor:1.23},{name:"Winchester",code:"194",factor:1.23},{name:"Antracita Veteado",code:"523",factor:1.22},{name:"Antracita",code:"408",factor:1.22},{name:"Black Ulti Matt",code:"192",factor:1.25},{name:"Gris Aluminio",code:"911",factor:1.22},{name:"Truffle Oak",code:"422",factor:1.24},{name:"Nogal Ulti Matt",code:"456",factor:1.25}]
};

const money=(v:number)=>v.toLocaleString("es-MX",{style:"currency",currency:"MXN"});

export default function Home(){
  const [brand,setBrand]=useState<Brand>("Aluplast"); const [systemIndex,setSystemIndex]=useState(0); const [layoutId,setLayoutId]=useState("slide2"); const [rail,setRail]=useState(2);
  const [width,setWidth]=useState(4000); const [height,setHeight]=useState(2200); const [qty,setQty]=useState(1); const [glassIndex,setGlassIndex]=useState(7); const [colorIndex,setColorIndex]=useState(1); const [face,setFace]=useState("Ambas caras");
  const [tab,setTab]=useState<Tab>("Diseño"); const [view,setView]=useState<ViewMode>("Frente"); const [report,setReport]=useState<Report>("Vidrio"); const [margin,setMargin]=useState(35); const [installation,setInstallation]=useState(1200); const [transport,setTransport]=useState(450); const [discount,setDiscount]=useState(0); const [code,setCode]=useState("001"); const [designation,setDesignation]=useState("V01"); const [location,setLocation]=useState("Cocina"); const [showLibrary,setShowLibrary]=useState(false);
  const [selectedPane,setSelectedPane]=useState(0); const [paneSpecs,setPaneSpecs]=useState<PaneSpec[]>(Array.from({length:6},(_,i)=>({state:i===0?"Móvil":"Fija",opening:i===0?"Corredera":"Sin apertura",direction:i===0?"Derecha":"N/A",hardware:i===0?"Roto · juego corredera":"Sin herraje",handle:i===0?"Harmony con tetones":"Sin manilla",glass:"Heredar vidrio general",notes:""})));
  const sys=catalog[brand][Math.min(systemIndex,catalog[brand].length-1)]; const layout=layouts.find(x=>x.id===layoutId) ?? layouts[1]; const glass=glassCatalog[glassIndex]; const color=colors[brand][Math.min(colorIndex,colors[brand].length-1)];
  const validLayouts=layouts.filter(x=>sys.layouts.includes(x.id));
  const changeBrand=(b:Brand)=>{setBrand(b);setSystemIndex(0);setColorIndex(0);const s=catalog[b][0];setLayoutId(s.layouts[0]);setRail(s.rails[0]);};
  const changeSystem=(i:number)=>{setSystemIndex(i);const s=catalog[brand][i];setLayoutId(s.layouts[0]);setRail(s.rails[0]);};
  const updatePane=(key:keyof PaneSpec,value:string)=>setPaneSpecs(p=>p.map((x,i)=>i===selectedPane?{...x,[key]:value}:x));
  const calc=useMemo(()=>{const w=width/1000,h=height/1000,area=w*h,perimeter=2*(w+h),panelW=width/layout.panels; const frameM=perimeter+(layout.panels-1)*h; const sashM=layout.panels*2*(panelW/1000+h); const profileCost=(frameM*sys.frame+sashM*sys.sash)*color.factor; const glassArea=Math.max(0,(w-.12)*(h-.12)); const glassCost=glassArea*glass.price; const reinforce=(frameM+sashM)*78; const seals=(frameM+sashM)*24; const accessories=sys.hardware+(layout.panels*110)+(rail*165); const consumables=(profileCost+glassCost)*.045; const direct=profileCost+glassCost+reinforce+seals+accessories+consumables+installation+transport; const sale=direct/(1-margin/100)*(1-discount/100); const bars=Math.ceil((frameM+sashM)/6); return{w,h,area,perimeter,panelW,frameM,sashM,glassArea,profileCost,glassCost,reinforce,seals,accessories,consumables,direct,sale,total:sale*qty,utility:(sale-direct)*qty,bars,waste:Math.max(0,bars*6-frameM-sashM),glassW:Math.max(100,Math.round(panelW-120)),glassH:Math.max(100,height-120)}},[width,height,layout,sys,color,glass,rail,installation,transport,margin,discount,qty]);
  const warnings=[...(width>sys.maxW||height>sys.maxH?[`Medida supera el límite de referencia ${sys.maxW} × ${sys.maxH} mm.`]:[]),...(glass.thickness>sys.glazing?[`Vidrio de ${glass.thickness} mm supera el galce de referencia (${sys.glazing} mm).`]:[]),...(rail>0&&!sys.rails.includes(rail)?[`El sistema no contempla ${rail} riel(es).`]:[])];

  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brandMark">L</span><span>LUFT <b>PVC</b></span></a><div className="projectName"><span>PROYECTO ACTIVO</span><strong>Oferta {code} · {designation} {location}</strong></div><div className="headerActions"><button className="ghost" onClick={()=>setShowLibrary(!showLibrary)}>Biblioteca de diseños</button><button className="primary" onClick={()=>window.print()}>Generar informe</button></div></header>
    <nav className="moduleNav">{(["Resumen","Diseño","Consumo","Servicios","Informes"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
    {showLibrary&&<section className="library"><div className="libraryHead"><div><b>Biblioteca de ventanas y puertas</b><span>{validLayouts.length} diseños compatibles con {sys.name}</span></div><button onClick={()=>setShowLibrary(false)}>Cerrar ×</button></div><div className="layoutCards">{validLayouts.map(x=><button key={x.id} className={layoutId===x.id?"selected":""} onClick={()=>{setLayoutId(x.id);setRail(x.rails)}}><strong>{x.icon}</strong><span>{x.name}</span><small>{x.group}{x.rails?` · ${x.rails} riel${x.rails>1?"es":""}`:""}</small></button>)}</div></section>}

    <section className="workspace" id="top">
      <aside className="configPanel">
        <div className="eyebrow">MOTOR DE CONFIGURACIÓN · MX</div><h1>{tab}</h1><p className="lead">Sistema técnico de diseño, consumo y cotización para cancelería de PVC.</p>
        {tab==="Resumen"&&<><Block n="01" title="Proyecto y cliente" sub="Datos que aparecerán en la oferta."/><div className="inputGrid two"><label>Código<input value={code} onChange={e=>setCode(e.target.value)}/></label><label>Designación<input value={designation} onChange={e=>setDesignation(e.target.value)}/></label></div><label>Ubicación / descripción<input value={location} onChange={e=>setLocation(e.target.value)}/></label><div className="summaryCard"><span>Marca</span><b>{brand}</b><span>Sistema</span><b>{sys.name}</b><span>Configuración</span><b>{layout.name}</b><span>Superficie total</span><b>{(calc.area*qty).toFixed(3)} m²</b></div></>}
        {tab==="Diseño"&&<><Block n="01" title="Marca y sistema" sub="Catálogo técnico del proyecto."/><div className="segmented"><button className={brand==="Aluplast"?"selected":""} onClick={()=>changeBrand("Aluplast")}>ALUPLAST</button><button className={brand==="Deceuninck"?"selected":""} onClick={()=>changeBrand("Deceuninck")}>DECEUNINCK</button></div><label>Sistema<select value={systemIndex} onChange={e=>changeSystem(Number(e.target.value))}>{catalog[brand].map((x,i)=><option key={x.name} value={i}>{x.name}</option>)}</select></label><label>Configuración<select value={layoutId} onChange={e=>{const id=e.target.value;setLayoutId(id);setRail(layouts.find(x=>x.id===id)?.rails??0)}}>{validLayouts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{sys.rails.some(x=>x>0)&&<label>Tipo de riel<select value={rail} onChange={e=>setRail(Number(e.target.value))}>{sys.rails.map(x=><option key={x} value={x}>{x===1?"Monorriel":`${x} rieles`}</option>)}</select></label>}<Block n="02" title="Geometría" sub="Cotas generales en milímetros."/><div className="inputGrid"><label>Ancho<input type="number" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label><label>Alto<input type="number" value={height} onChange={e=>setHeight(Number(e.target.value))}/></label><label>Cant.<input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label></div><Block n="03" title="Materiales" sub="Color, aplicación y vidrio."/><label>Color / folio<select value={colorIndex} onChange={e=>setColorIndex(Number(e.target.value))}>{colors[brand].map((x,i)=><option value={i} key={x.code}>{x.code} · {x.name}</option>)}</select></label><div className="inputGrid two"><label>Aplicación<select value={face} onChange={e=>setFace(e.target.value)}><option>Exterior</option><option>Interior</option><option>Ambas caras</option></select></label><label>Vidrio<select value={glassIndex} onChange={e=>setGlassIndex(Number(e.target.value))}>{glassCatalog.map((x,i)=><option key={x.name} value={i}>{x.name}</option>)}</select></label></div></>}
        {tab==="Consumo"&&<><Block n="01" title="Optimización de corte" sub="Patrones preliminares sobre barras comerciales de 6 m."/><div className="optimization"><strong>{calc.bars}</strong><span>barras estimadas</span><b>{calc.waste.toFixed(2)} m</b><span>remanente teórico</span></div><label>Longitud de barra<select><option>6,000 mm</option><option>6,500 mm</option></select></label><div className="cutPlan">{Array.from({length:Math.min(calc.bars,6)},(_,i)=>{const pieces=i<2?[width,height]:[Math.round(calc.panelW),height,Math.round(calc.panelW)];const used=Math.min(5800,pieces.reduce((a,b)=>a+b,0));return <div key={i}><header><b>Barra {String(i+1).padStart(2,"0")}</b><span>{used} / 6000 mm</span></header><section>{pieces.map((p,j)=><i key={j} style={{width:`${Math.max(12,p/60)}%`}}>{p}</i>)}<em style={{flex:1}}>{Math.max(0,6000-used)}</em></section></div>})}</div><p className="notice">La optimización definitiva depende de descuentos, ángulos, soldadura, refuerzos, sierra y reglas específicas del catálogo.</p>{brand==="Aluplast"&&<><Block n="02" title="Perfiles IDEAL 2000" sub="Códigos identificados en catálogo y listas MX."/><div className="profileCatalog">{ideal2000Profiles.map(p=><div key={p.code}><span className="profileSketch">{p.role==="Conector"?"⊞":p.role==="Junquillo"?"⌝":"▥"}</span><section><b>{p.code}</b><p>{p.name}</p><small>{p.role} · {p.status}</small></section></div>)}</div></>}</>}
        {tab==="Servicios"&&<><Block n="01" title="Costos adicionales" sub="Recargos y condiciones comerciales."/><label>Instalación por pieza<input type="number" value={installation} onChange={e=>setInstallation(Number(e.target.value))}/></label><label>Transporte por pieza<input type="number" value={transport} onChange={e=>setTransport(Number(e.target.value))}/></label><label>Margen de utilidad <b>{margin}%</b><input type="range" min="10" max="60" value={margin} onChange={e=>setMargin(Number(e.target.value))}/></label><label>Descuento <b>{discount}%</b><input type="range" min="0" max="20" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label></>}
        {tab==="Informes"&&<><Block n="01" title="Centro de informes" sub="Selecciona el documento y genera PDF."/><div className="reportList">{(["Oferta","Producción","Perfiles","Herrajes","Vidrio","Costos"] as Report[]).map(r=><button className={report===r?"selected":""} key={r} onClick={()=>setReport(r)}>{r}<span>Ver →</span></button>)}</div><button className="fullButton" onClick={()=>window.print()}>Exportar {report} a PDF <span>↗</span></button></>}
      </aside>

      <section className="visualPanel">
        <div className="visualHeader"><div><span className="statusDot"/>VISTA {view.toUpperCase()} · {layout.name.toUpperCase()}</div><div className="viewSwitch">{(["Frente","Sección","3D"] as ViewMode[]).map(v=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{v}</button>)}</div></div>
        <div className={`canvas view-${view.replace("ó","o")}`}><div className="dim top"><span>W={width.toLocaleString()} mm</span></div><div className="dim side"><span>H={height.toLocaleString()} mm</span></div>{view==="Sección"?<SectionRender depth={sys.depth} rail={rail} glazing={glass.thickness}/>:<div className="modelStage"><WindowRender layout={layout} color={color.name} specs={paneSpecs} selected={selectedPane} onSelect={setSelectedPane}/>{view==="3D"&&<><span className="modelSide"/><span className="modelSill"/></>}</div>}<div className="editHint">Haz clic en una hoja para editarla</div><div className="panelDimensions">{Array.from({length:layout.panels},(_,i)=><span key={i}>{Math.round(width/layout.panels).toLocaleString()}</span>)}</div><div className="specChip"><b>{brand} · {sys.name}</b><span>{sys.depth} mm · {sys.chambers} · {rail?`${rail} riel${rail>1?"es":""}`:"practicable"}</span><span>{glass.name} · {face}</span></div></div>
        <div className="metricRow"><div><span>SUPERFICIE</span><strong>{calc.area.toFixed(3)} m²</strong></div><div><span>VIDRIO ÚTIL</span><strong>{calc.glassArea.toFixed(3)} m²</strong></div><div><span>PANEL APROX.</span><strong>{calc.glassW} × {calc.glassH}</strong></div><div><span>REFERENCIA</span><strong>{code}-{designation}</strong></div></div>
      </section>

      <aside className="quotePanel">
        <div className="quoteHead"><div><span>PROPIEDADES</span><strong>{designation}</strong></div><span className={`badge ${warnings.length?"warning":""}`}>{warnings.length?`${warnings.length} alerta${warnings.length>1?"s":""}`:"Compatible"}</span></div>
        {warnings.length>0&&<div className="warnings">{warnings.map(x=><p key={x}>⚠ {x}</p>)}</div>}
        {tab==="Diseño"&&<div className="componentEditor"><div className="componentTitle"><span>COMPONENTE SELECCIONADO</span><b>Hoja {String.fromCharCode(65+selectedPane)}</b><small>{Math.round(width/layout.panels)} × {height} mm</small></div><div className="componentGrid"><label>Estado<select value={paneSpecs[selectedPane].state} onChange={e=>updatePane("state",e.target.value)}><option>Fija</option><option>Móvil</option><option>Inactiva</option></select></label><label>Tipo de apertura<select value={paneSpecs[selectedPane].opening} onChange={e=>updatePane("opening",e.target.value)}><option>Sin apertura</option><option>Corredera</option><option>Abatible interior</option><option>Abatible exterior</option><option>Oscilobatiente</option><option>Proyectante</option></select></label><label>Dirección<select value={paneSpecs[selectedPane].direction} onChange={e=>updatePane("direction",e.target.value)}><option>N/A</option><option>Derecha</option><option>Izquierda</option><option>Interior</option><option>Exterior</option></select></label><label>Vidrio<select value={paneSpecs[selectedPane].glass} onChange={e=>updatePane("glass",e.target.value)}><option>Heredar vidrio general</option>{glassCatalog.map(x=><option key={x.name}>{x.name}</option>)}</select></label><label className="wide">Herraje<select value={paneSpecs[selectedPane].hardware} onChange={e=>updatePane("hardware",e.target.value)}><option>Sin herraje</option><option>Roto · juego corredera</option><option>Roto · carros 80 kg</option><option>Roto · carros 120 kg</option><option>Roto · cierre multipunto</option><option>Roto Patio · osciloparalela</option><option>Bisagras reforzadas</option></select></label><label className="wide">Manilla / cierre<select value={paneSpecs[selectedPane].handle} onChange={e=>updatePane("handle",e.target.value)}><option>Sin manilla</option><option>Harmony con tetones</option><option>Slim 479092 con tetones</option><option>Cierre embutido</option><option>Manillón doble</option><option>Cremona multipunto</option></select></label><label className="wide">Observaciones<textarea value={paneSpecs[selectedPane].notes} onChange={e=>updatePane("notes",e.target.value)} placeholder="Mecanizado, altura de manilla, restricciones..."/></label></div><p className="componentNote">Selecciona carros, cierres y manillas según el peso del vidrio, tamaño de hoja y geometría del perfil.</p></div>}
        {tab==="Informes"?<ReportPreview report={report} code={code} designation={designation} location={location} brand={brand} system={sys.name} layout={layout} qty={qty} width={width} height={height} glass={glass.name} calc={calc}/>:<><div className="propertyGroup"><h2>Información general</h2><Prop k="Nombre completo" v={`${designation} · ${location}`}/><Prop k="Referencia" v={`${code}.${brand.slice(0,3).toUpperCase()}.${layout.id.toUpperCase()}`}/><Prop k="Tipo de panel" v={layout.group}/><Prop k="Apertura" v={layout.name}/><Prop k="Riel inferior" v={rail?String(rail):"N/A"}/></div>
        <div className="propertyGroup"><h2>Geometría</h2><Prop k="Forma" v="Rectángulo"/><Prop k="W" v={`${width.toLocaleString()} mm`}/><Prop k="H" v={`${height.toLocaleString()} mm`}/><Prop k="Perímetro" v={`${calc.perimeter.toFixed(3)} m`}/><Prop k="Superficie" v={`${calc.area.toFixed(3)} m²`}/></div>
        <div className="propertyGroup"><h2>Prestaciones del sistema</h2><Prop k="Profundidad" v={`${sys.depth} mm`}/><Prop k="Acristalamiento máx." v={`${sys.glazing} mm`}/><Prop k="Valor Uf" v={sys.uf}/><Prop k="Límite de referencia" v={`${sys.maxW} × ${sys.maxH} mm`}/></div>
        <div className="costSummary"><h2>Costos del elemento</h2><Cost label="Perfiles" value={calc.profileCost}/><Cost label="Accesorios y herrajes" value={calc.accessories+calc.reinforce+calc.seals}/><Cost label="Vidrio" value={calc.glassCost}/><Cost label="Servicios y consumibles" value={installation+transport+calc.consumables}/><div className="direct"><span>Costo directo / pza.</span><b>{money(calc.direct)}</b></div></div>
        <div className="totalBox"><span>TOTAL OFERTA <small>IVA no incluido</small></span><strong>{money(calc.total)}</strong><div><span>Utilidad estimada</span><b>{money(calc.utility)}</b></div></div>
        <details className="materials" open><summary>Consumo calculado</summary><Item code="PVC-MARCO" name="Marco / riel" qty={`${calc.frameM.toFixed(2)} m`}/><Item code="PVC-HOJA" name="Perfil de hoja" qty={`${calc.sashM.toFixed(2)} m`}/><Item code="VIDRIO" name={glass.name} qty={`${calc.glassArea.toFixed(3)} m²`}/><Item code="REF-AC" name="Refuerzo galvanizado" qty={`${(calc.frameM+calc.sashM).toFixed(2)} m`}/><Item code="EPDM" name="Juntas y sellos" qty={`${(calc.frameM+calc.sashM).toFixed(2)} m`}/><Item code="HERRAJE" name="Juego de herrajes" qty={`${layout.panels} set`}/></details>
        <p className="priceNote">Motor técnico v2 · Valores en MXN. Los precios y límites deben validarse con la lista vigente y la ingeniería de cada proyecto.</p></>}
      </aside>
    </section>
    <footer className="sources"><b>Base técnica:</b> documentación RA Workshop aportada, <a href="https://www.aluplast.net/eng-int/products/windows/ideal/" target="_blank">sistemas oficiales Aluplast</a> y <a href="https://www.deceuninck.com.mx/en/pdf/catalogo_tecnico.pdf" target="_blank">catálogo técnico Deceuninck México</a>.</footer>
  </main>
}

function WindowRender({layout,color,specs,selected,onSelect}:{layout:Layout;color:string;specs:PaneSpec[];selected:number;onSelect:(i:number)=>void}){const light=color==="Blanco";return <div className={`window ${light?"whiteFrame":""}`} style={{gridTemplateColumns:`repeat(${layout.panels},1fr)`}}>{Array.from({length:layout.panels},(_,i)=>{const s=specs[i];const arrow=s.direction==="Derecha"?"→":s.direction==="Izquierda"?"←":s.opening==="Sin apertura"?"FIJO":"◁";return <button type="button" aria-label={`Editar hoja ${String.fromCharCode(65+i)}`} className={`pane ${selected===i?"selectedPane":""}`} key={i} onClick={()=>onSelect(i)}><span className="motion">{arrow}</span>{s.opening!=="Sin apertura"&&!s.opening.includes("Corredera")&&<i className="openingLines"/>}<em>{String.fromCharCode(65+i)} · {s.state}</em><small className="paneHardware">{s.hardware.replace("Roto · ","")}</small></button>})}</div>}
function SectionRender({depth,rail,glazing}:{depth:number;rail:number;glazing:number}){return <div className="sectionRender"><div className="profileSection"><span className="chamber c1"/><span className="chamber c2"/><span className="chamber c3"/><i className="glassSection" style={{width:`${Math.max(8,glazing/2)}px`}}/></div><div className="sectionInfo"><b>Sección de sistema</b><span>Profundidad: {depth} mm</span><span>Acristalamiento: {glazing} mm</span><span>{rail?`${rail} riel${rail>1?"es":""}`:"Doble contacto"}</span></div></div>}
function Block({n,title,sub}:{n:string;title:string;sub:string}){return <div className="step"><span>{n}</span><div><b>{title}</b><small>{sub}</small></div></div>}
function Prop({k,v}:{k:string;v:string}){return <div className="prop"><span>{k}</span><b>{v}</b></div>}
function Cost({label,value}:{label:string;value:number}){return <div className="line"><span>{label}</span><b>{money(value)}</b></div>}
function Item({code,name,qty}:{code:string;name:string;qty:string}){return <div className="materialItem"><span>{code}</span><div><b>{name}</b><small>{qty}</small></div></div>}
function ReportPreview({report,code,designation,location,brand,system,layout,qty,width,height,glass,calc}:{report:Report;code:string;designation:string;location:string;brand:Brand;system:string;layout:Layout;qty:number;width:number;height:number;glass:string;calc:any}){return <div className="reportPreview"><header><span>LUFT PVC · {report.toUpperCase()}</span><b>{code} / {designation}</b><small>{location} · {brand} · {system}</small></header>{report==="Vidrio"?<><h3>Orden de vidrio</h3><table><thead><tr><th>Pos.</th><th>Descripción</th><th>Cant.</th><th>Medidas</th><th>m²</th></tr></thead><tbody>{Array.from({length:layout.panels},(_,i)=><tr key={i}><td>{designation}.{String.fromCharCode(65+i)}</td><td>{glass}</td><td>{qty}</td><td>{calc.glassW} × {calc.glassH}</td><td>{(calc.glassW/1000*calc.glassH/1000*qty).toFixed(3)}</td></tr>)}</tbody><tfoot><tr><th colSpan={4}>Superficie total</th><th>{(calc.glassArea*qty).toFixed(3)}</th></tr></tfoot></table></>:report==="Perfiles"?<><h3>Orden total de perfiles</h3><ReportRow a="Marco / riel" b={`${(calc.frameM*qty).toFixed(2)} m`} c={`${Math.ceil(calc.frameM*qty/6)} barras`}/><ReportRow a="Perfil de hoja" b={`${(calc.sashM*qty).toFixed(2)} m`} c={`${Math.ceil(calc.sashM*qty/6)} barras`}/><ReportRow a="Refuerzo" b={`${((calc.frameM+calc.sashM)*qty).toFixed(2)} m`} c="Galvanizado"/></>:report==="Herrajes"?<><h3>Accesorios y herrajes</h3><ReportRow a="Juego de herrajes" b={`${layout.panels*qty} set`} c={layout.name}/><ReportRow a="Juntas EPDM" b={`${((calc.frameM+calc.sashM)*qty).toFixed(2)} m`} c="Perimetral"/><ReportRow a="Calzos / topes" b={`${layout.panels*4*qty} pza`} c="Según vidrio"/></>:report==="Producción"?<><h3>Orden de producción</h3><ReportRow a="Elemento" b={`${qty} pza`} c={`${width} × ${height} mm`}/><ReportRow a="Apertura" b={layout.name} c={`${layout.panels} paneles`}/><ReportRow a="Vidrio" b={glass} c={`${calc.glassW} × ${calc.glassH}`}/><ReportRow a="Control" b="Medidas y diagonales" c="Pendiente"/></>:report==="Costos"?<><h3>Estadística del proyecto</h3><ReportRow a="Perfiles" b={money(calc.profileCost*qty)} c="MXN"/><ReportRow a="Vidrio" b={money(calc.glassCost*qty)} c="MXN"/><ReportRow a="Herrajes y accesorios" b={money(calc.accessories*qty)} c="MXN"/><ReportRow a="Costo directo" b={money(calc.direct*qty)} c="MXN"/><ReportRow a="Total oferta" b={money(calc.total)} c="MXN"/></>:<><h3>Oferta para cliente</h3><ReportRow a={`${designation} · ${location}`} b={`${qty} pza`} c={`${width} × ${height} mm`}/><ReportRow a={brand} b={system} c={layout.name}/><ReportRow a="Total" b={money(calc.total)} c="IVA no incluido"/></>}</div>}
function ReportRow({a,b,c}:{a:string;b:string;c:string}){return <div className="reportRow"><span>{a}</span><b>{b}</b><small>{c}</small></div>}
